// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNghiPhep.WebApp.Data;

#nullable disable

namespace QuanLyNghiPhep.WebApp.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250723093525_23072025")]
    partial class _23072025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Department", b =>
                {
                    b.Property<string>("Department_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Department_id");

                    b.HasIndex("ParentId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.DepartmentEmployee", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("EmployeeIsManager")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DepartmentEmployee");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Employee", b =>
                {
                    b.Property<string>("Employee_ID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Employee_ID");

                    b.HasIndex("Title_id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Employee_id")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RemainingDays")
                        .HasColumnType("int");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Employee_id");

                    b.ToTable("LeaveBalance");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedById")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Employee_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextApproverId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Employee_id");

                    b.HasIndex("NextApproverId");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Roles", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_ID"));

                    b.Property<string>("Role_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Titles", b =>
                {
                    b.Property<string>("Title_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title_id");

                    b.ToTable("Title");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Employee_ID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Employee_ID")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Department", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Department", "Parent")
                        .WithMany("SubDepartments")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.DepartmentEmployee", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Department", "Department")
                        .WithMany("DepartmentEmployees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "Employee")
                        .WithMany("DepartmentEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Employee", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Titles", "Title")
                        .WithMany("Employees")
                        .HasForeignKey("Title_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Title");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.LeaveBalance", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.LeaveRequest", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "ApprovedBy")
                        .WithMany("ApprovedLeaveRequests")
                        .HasForeignKey("ApprovedById");

                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "NextApprover")
                        .WithMany()
                        .HasForeignKey("NextApproverId");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("NextApprover");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Log", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.User", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Employee", "EmployeeUs")
                        .WithOne("User")
                        .HasForeignKey("QuanLyNghiPhep.WebApp.Models.User", "Employee_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeUs");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.UserRole", b =>
                {
                    b.HasOne("QuanLyNghiPhep.WebApp.Models.Roles", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyNghiPhep.WebApp.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Department", b =>
                {
                    b.Navigation("DepartmentEmployees");

                    b.Navigation("SubDepartments");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Employee", b =>
                {
                    b.Navigation("ApprovedLeaveRequests");

                    b.Navigation("DepartmentEmployees");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.Titles", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("QuanLyNghiPhep.WebApp.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
